### ISSUE TITLE
Create the dashboard page

### ISSUE THREAD

**Issue by IagoGoncalves22** [IagoGoncalves22/easy-store#5]
# Context

Our users needs a dashboard page with the options.

* Figma: https://www.figma.com/file/Rr0Fl9UNDeCUAAFHTvHi86/Iago-Project?node-id=3%3A56&t=DJ1YQ0Dj5BctjAUV-0

# Tech planning

*tbd

# Aceptanece criteria

* there is a url for the dashboard page. For now it's not functioning, just the UI.

**Comment by galexandrade** [comment]
I'm obsoleting this issue because it was already implemented as part of https://github.com/IagoGoncalves22/easy-store/issues/4
