### ISSUE TITLE
Create customer list page

### ISSUE THREAD

**Issue by IagoGoncalves22** [IagoGoncalves22/easy-store#6]
# Context

Our users needs a customer list page with a link to list the customers.

* Figma: https://www.figma.com/file/Rr0Fl9UNDeCUAAFHTvHi86/Iago-Project?node-id=3%3A147&t=DJ1YQ0Dj5BctjAUV-0

<img width="866" alt="image" src="https://user-images.githubusercontent.com/24475665/229247501-d757e25a-51ad-4d6b-bd06-f0351b5962f2.png">

## Details

Most of this page was already implemented as part of https://github.com/IagoGoncalves22/easy-store/issues/4.

# Tech AC:

- Update the `src/pages/CustomerPage.tsx` to change the `ITEMS` to have only:
   - `id`: any number for now
   - `name`: the customer name
   - `nickname`: the customer nickname
- We don't need the existing `date`, `hours` and `image`
- Make sure it looks like the one in the design

# Aceptanece criteria

* there is a url for the customer list page. For now it's not functioning, just the UI.

**Comment by galexandrade** [comment]
I'm obsoleting this issue because it was already implemented as part of https://github.com/IagoGoncalves22/easy-store/issues/4

**Comment by galexandrade** [comment]
Reopening it again as I noticed a couple of things that needs to be implemented on the table to be like in Figma.
